//every file is a module(by default)
const names=require('./names')
const sayHi_fn=require('./utils')
const data=require('./alternative-flavor')
require('./mind-grenade')
console.log(names)
console.log(data)
sayHi_fn("susan")
sayHi_fn(names.john)
sayHi_fn(names.peter)